const CONST = {
  COUNTER: {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    UPDATE_VALUE: 'UPDATE_VALUE',
    INCREMENT_IF_ODD: 'INCREMENT_IF_ODD',
    INCREMENT_ASYNC: 'INCREMENT_ASYNC'
  },
  ABM: {
    SAVE: 'SAVE',
    CANCEL: 'CANCEL',
    UPDATE_TEXT: 'UPDATE_TEXT',
    FAILS: 'FAILS'
  }
};

export default CONST;
